### ISSUE TITLE
The Good Form, The Bad Form, and the downright Ugly Form

### ISSUE THREAD

**Issue by mordrax** [elmsydney/elmsydney#10]
### Summary
Not to be confused with Intumescent Foam, Military FORMations or frankly, any other english term in the dictionary, this talk is about creating UI Forms in Elm.

As usual, yours truly starts off with some pretty horrendous ignorant design and as we blunder through requirements and explore what the language can provide, we come up with alternatives to the initial design which has it's pros and cons.

This is a talk about how UI Forms has evolved with reuse, flexibility, modularity in mind.
Note: This is a 'share our experience' kind of talk, not a 'we found _the_ way to do forms' sort

### Info
- Which month's meetup you would like to present at: February
- Type of talk: Full-length talk with coding
- mordraxx@twitter
- *Not* my Linkedin pic

**Comment by paulfioravanti** [comment]
Thanks, @mordrax! If there's anything you want to share publicly, tweet it out to `@elmsydney` and we'll re-tweet it.
