### ISSUE TITLE
Exercism: Rains

### ISSUE THREAD

**Issue by r-k-b** [elmsydney/elmsydney#11]
#  Brief summary of the talk content

Discussing my solution(s) to the [Raindrops](https://exercism.io/tracks/elm/exercises/raindrops) exercise.

# Which month's meetup you would like to present at

Feb 2020

# Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

https://media-exp1.licdn.com/dms/image/C5103AQFsfLi9nWoHtw/profile-displayphoto-shrink_200_200/0?e=1587600000&v=beta&t=teZXGWawWQ4FvLElX4b9HuNpEyrNADBFsacFCZXw_58

**Comment by paulfioravanti** [comment]
Awesome, thanks @r-k-b! You're locked in for this month!

**Comment by paulfioravanti** [comment]
@r-k-b did you have a Twitter account?

**Comment by r-k-b** [comment]
[incredasterisk](https://twitter.com/incredasterisk), but I'm hardly on there.

**Comment by paulfioravanti** [comment]
Thanks, @r-k-b! If you end up pushing your solution up to the Exercism site, feel free to tweet out the link to the public link to the solution and we'll give it a re-tweet!
