### ISSUE TITLE
The Lazy Person's Guide to Elm Performance

### ISSUE THREAD

**Issue by justosophy-zz** [elmsydney/elmsydney#12]
Name of talk: "The Lazy Person's Guide to Elm Performance"

Brief summary of the talk content
Some practical examples of how to profile and improve performance in an Elm application. Knowing how and when.
Some unexpected examples of performance issues and how they were addressed in an application.
Some *impractical* examples of improving performance by editing the Elm run time.

Which month's meetup you would like to present at: Thursday, February 27, 2020

Length of talk: Up to 30 min. Possibly less.

Your Twitter username: https://twitter.com/justosophy

Profile image: https://www.linkedin.com/in/justinivananderson/

**Comment by paulfioravanti** [comment]
Awesome! Thanks @justosophy! You're on for February!

**Comment by paulfioravanti** [comment]
Thanks @justosophy! If you share your slides somewhere publicly, please tweet them out to `@elmsydney`!
