### ISSUE TITLE
Elm's Types Made Simple

### ISSUE THREAD

**Issue by damncabbage** [elmsydney/elmsydney#2]
(Full-length, September meetup)

A casual walk through of Elm's types, from the basic building blocks upwards. You'll come away from this with a firmer grasp of both basic and more complicated types in Elm, and how you might use them to make your code safer.

[This will be partly live-coding; given the likely size of the audience, we can spend more time on some areas or speed up as needed.]

---

Profile picture:

![Photo on 13-8-19 at 10 53 am copy](https://user-images.githubusercontent.com/133028/65556090-c58a8980-df71-11e9-9768-06833b5eecb5.jpg)

**Comment by paulfioravanti** [comment]
:+1: for profile pic

**Comment by paulfioravanti** [comment]
Dunno if you have the code you used last night up in a repo or gist, but if you do, tweet it on over to `@elmsydney` and we'll retweet it. Thanks for helping me kick things off last night!
