### ISSUE TITLE
Intro to reusable views in elm

### ISSUE THREAD

**Issue by David-Factor** [elmsydney/elmsydney#3]
This talk provides a quick guide to building reusable view functions in elm.

When I first started using Elm, transitioning from react and vuejs, the first thing I wanted to do was make all my UI widgets into reusable components. After much hand wringing, it turned out that many concepts from react and other mainstream js frameworks, didn't directly translate over to the more strict world of Elm. 

This talk is intended to show how I transitioned away from components and embraced an approach to building reusable views in elm.

I start the talk with an example of a simple reusable button, before building the example into a more complex configurable view with state and side-effects.

**Comment by paulfioravanti** [comment]
Thanks @David-Factor! Locked in for October!

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @David-Factor ! If you have your code in a gist somewhere, please tweet it out to `@elmsydney` and we'll give it a retweet and add it to the README for this month.
