### ISSUE TITLE
Exercism: solution to leap

### ISSUE THREAD

**Issue by garethstokes** [elmsydney/elmsydney#4]
This is a lightning talk where I will go through my solution to the Leap problem that can be found on the exercism.io website. 

https://exercism.io/tracks/elm/exercises/leap

**Comment by paulfioravanti** [comment]
Thanks @garethstokes! Locked in for tomorrow!

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @garethstokes ! What's the link to your actual Exercism solution? If you want, please tweet it out to `@elmsydney` and we'll give it a retweet and add it to the README for this month.
