### ISSUE TITLE
Random Generators for a RoseTree

### ISSUE THREAD

**Issue by justosophy-zz** [elmsydney/elmsydney#5]
Title: Random Generators for a RoseTree
Description: Two approaches used to add random pairing to a rosetree datastructure.
Twitter: @justosophy
Type of talk: Lightning talk
Date: 24th October 2019

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @justosophy! If you have any materials that you want to share, tweet them out to `@elmsydney` and we'll give it a retweet and add it to the README for this month.
