### ISSUE TITLE
Castle of the Winds, a top down turn based rpg written in Elm

### ISSUE THREAD

**Issue by mordrax** [elmsydney/elmsydney#6]
Castle of the Winds is a turn based RPG game made for the Windows 3.1 by Rick Saada in 1989.
It was the game that started my love for creating things with computers and I have been attempting to rewrite this game for the better part of my career.

Concepts that I'll be covering may include, but not limited to:
- rendering
- input
- dungeon generation
- A* pathfinding
- monster balancing
- inventory
- drag and drop
- fov
- game loop

Month: Nov if possible
Type of talk: Maybe 5 minutes per concept, I'll try to keep it to 30mins + question/demo
Twitter: @mordraxx
Photo: Please use my github avatar, it is from the game

**Comment by paulfioravanti** [comment]
@mordrax you are locked in for November!
