### ISSUE TITLE
Exercism nucleotide exercise

### ISSUE THREAD

**Issue by venkateshpitta** [elmsydney/elmsydney#7]
Nucleotide exercise from exercism.io
~5 minutes talk

**Comment by paulfioravanti** [comment]
@venkateshpitta do you have a Twitter account by any chance, and a profile photo of yourself?

**Comment by paulfioravanti** [comment]
Hey @venkateshpitta what happened tonight? Everything okay? I ended up doing the lightning talk in your stead, but if you want to do one in the future, let us know.
