### ISSUE TITLE
A little tile editor in Elm (using `Platform.worker`)

### ISSUE THREAD

**Issue by justosophy-zz** [elmsydney/elmsydney#9]
Title: A little tile editor in Elm (using `Platform.worker`)

Description: Using JS for the renderer and Elm Platform.worker program for the game logic.

Twitter: https://twitter.com/justosophy

Meetup: November

Type of talk: Lightning talk

**Comment by paulfioravanti** [comment]
Added this talk to this month's README for the record :+1:
